# Generated by Django 3.1.5 on 2021-01-25 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproperties',
            name='customer_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cportal.locationinfo'),
            preserve_default=False,
        ),
    ]
