# Generated by Django 3.1.5 on 2021-01-29 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0002_auto_20210125_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproperties',
            name='connected_device',
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='user_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerproperties',
            name='connected_interface',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cportal.interfaceinfo'),
            preserve_default=False,
        ),
    ]
