# Generated by Django 3.1.5 on 2021-01-29 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0003_auto_20210129_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproperties',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
