# Generated by Django 3.1.5 on 2021-01-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0004_auto_20210129_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproperties',
            name='connected_interface',
        ),
        migrations.AddField(
            model_name='customerproperties',
            name='connected_interface',
            field=models.ManyToManyField(to='Cportal.InterfaceInfo'),
        ),
    ]
