# Generated by Django 3.1.5 on 2021-02-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0006_auto_20210130_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='device_type',
            field=models.CharField(choices=[('Router', 'Router'), ('Switch', 'Switch')], max_length=100, null=True),
        ),
    ]
