# Generated by Django 3.1.5 on 2021-02-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0007_deviceinfo_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproperties',
            name='peering_IP',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
