# Generated by Django 3.1.5 on 2021-03-08 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0008_customerproperties_peering_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='device_location',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='Cportal.locationinfo'),
            preserve_default=False,
        ),
    ]
