# Generated by Django 3.1.5 on 2021-03-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0009_deviceinfo_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='device_IP',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
