# Generated by Django 3.1.5 on 2021-03-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0010_deviceinfo_device_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceinfo',
            name='interface_graph',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
