# Generated by Django 3.1.5 on 2021-03-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0011_interfaceinfo_interface_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproperties',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cportal.customerinfo'),
        ),
    ]
