# Generated by Django 3.1.5 on 2021-03-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0014_auto_20210311_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerproperties',
            old_name='name',
            new_name='username',
        ),
    ]
