# Generated by Django 3.1.5 on 2021-03-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0015_auto_20210311_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='user_info',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='customerproperties',
            old_name='username',
            new_name='name',
        ),
    ]
