# Generated by Django 3.1.5 on 2021-05-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0016_auto_20210311_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproperties',
            name='ASN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
