# Generated by Django 3.1.5 on 2021-05-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0017_customerproperties_asn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproperties',
            name='peering_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
