# Generated by Django 3.1.5 on 2021-06-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0019_emailalertdb_phonealertdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
