# Generated by Django 3.1.5 on 2021-06-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0020_customerinfo_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
