# Generated by Django 3.1.5 on 2021-06-06 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cportal', '0021_customerinfo_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default-logo.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='emailalertdb',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phonealertdb',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
